"""Expand medical abbreviations in Short MCQ stems and choices to full words."""
from __future__ import annotations

import re

# Applied first (order matters)
PHRASE_EXPANSIONS: list[tuple[str, str]] = [
    (r'\bC1-INH\b', 'C1 esterase inhibitor'),
    (r'\bH2RA\b', 'histamine-2 receptor antagonist'),
    (r'\bH2RAs\b', 'histamine-2 receptor antagonists'),
    (r'\bNi\s*Ti\b', 'nickel-titanium'),
    (r'\bPML-RARA\b', 'promyelocytic leukemia/retinoic acid receptor alpha'),
    (r'\bBCR-ABL\b', 'breakpoint cluster region-Abelson'),
    (r'\bG6PD\b', 'glucose-6-phosphate dehydrogenase'),
    (r'\bRBCs\b', 'red blood cells'),
    (r'\bRBC\b', 'red blood cell'),
    ('\\bType\\s+I/IV\\b', 'Type 1/Type 4'),
    ('\\bType\\s+III/IV\\b', 'Type 3/Type 4'),
    ('\\bType\\s+II/III\\b', 'Type 2/Type 3'),
    ('\\bType\\s+IV\\b', 'Type 4'),
    ('\\bType\\s+III\\b', 'Type 3'),
    ('\\bType\\s+II\\b', 'Type 2'),
    ('\\bType\\s+I\\b', 'Type 1'),
    ('\\bclass\\s+IV\\b', 'class 4'),
    ('\\bclass\\s+III\\b', 'class 3'),
    ('\\bclass\\s+II\\b', 'class 2'),
    ('\\bclass\\s+I\\b', 'class 1'),
    ('\\bschedule\\s+IV\\b', 'schedule 4'),
    ('\\bschedule\\s+III\\b', 'schedule 3'),
    ('\\bschedule\\s+II\\b', 'schedule 2'),
    ('\\bCIV\\b', 'schedule 4'),
    ('\\bCIII\\b', 'schedule 3'),
    ('\\bCII\\b', 'schedule 2'),
    ('\\bACEI/ARB\\b', 'angiotensin-converting enzyme inhibitor/angiotensin receptor blocker'),
    ('\\bACEI\\b', 'angiotensin-converting enzyme inhibitor'),
    ('\\bACE inhibitor\\b', 'angiotensin-converting enzyme inhibitor'),
    ('\\bARBs?\\b', 'angiotensin receptor blocker'),
    ('\\bFEV1/FVC\\b', 'forced expiratory volume in 1 second/forced vital capacity'),
    ('\\bFEV1\\b', 'forced expiratory volume in 1 second'),
    ('\\bFVC\\b', 'forced vital capacity'),
    ('\\bDLCO\\b', 'diffusing capacity of the lung for carbon monoxide'),
    ('\\bST[- ]?segment[- ]elevation\\b', 'ST-segment elevation'),
    ('\\bST[- ]elevation\\b', 'ST-segment elevation'),
    ('\\bST[- ]depression\\b', 'ST-segment depression'),
    ('\\bin II,\\s*III,\\s*aVF\\b', 'in leads 2, 3, and aVF'),
    ('\\bin I/aVL\\b', 'in leads 1 and aVL'),
    ('\\bII,\\s*III,\\s*aVF\\b', 'leads 2, 3, and aVF'),
    ('\\bMLS practice\\b', 'medical laboratory science practice'),
    ('\\bQA vs QC\\b', 'quality assurance versus quality control'),
    ('\\bHFrEF\\b', 'heart failure with reduced ejection fraction'),
    ('\\bHFpEF\\b', 'heart failure with preserved ejection fraction'),
    ('\\bNSTEMI\\b', 'non-ST-segment-elevation myocardial infarction'),
    ('\\bSTEMI\\b', 'ST-segment-elevation myocardial infarction'),
    ('\\bDAPT\\b', 'dual antiplatelet therapy'),
    ('\\bPCI\\b', 'percutaneous coronary intervention'),
    ('\\bECG\\b', 'electrocardiogram'),
    ('\\bEKG\\b', 'electrocardiogram'),
    ('\\bCPR\\b', 'cardiopulmonary resuscitation'),
    ('\\bROSC\\b', 'return of spontaneous circulation'),
    ('\\bICU\\b', 'intensive care unit'),
    ('\\bED\\b', 'emergency department'),
    ('\\bOR\\b', 'operating room'),
    ('\\bNPO\\b', 'nothing by mouth'),
    ('\\bPRN\\b', 'as needed'),
    ('\\bBID\\b', 'twice daily'),
    ('\\bTID\\b', 'three times daily'),
    ('\\bQID\\b', 'four times daily'),
    ('\\bSTAT\\b', 'immediately'),
    ('\\bIVIG\\b', 'intravenous immunoglobulin'),
    ('\\bIM\\b', 'intramuscular'),
    ('\\bSC\\b', 'subcutaneous'),
    ('\\bSQ\\b', 'subcutaneous'),
    ('\\bPO\\b', 'by mouth'),
    ('\\bSL\\b', 'sublingual'),
]

TOKEN_EXPANSIONS: dict[str, str] = {
    'ADAMTS13': 'a disintegrin and metalloproteinase with thrombospondin type 1 motif member 13',
    'Asthma': 'asthma',
    'NSAIDs': 'nonsteroidal anti-inflammatory drugs',
    'NSTEMI': 'non-ST-segment-elevation myocardial infarction',
    'ADPKD': 'autosomal dominant polycystic kidney disease',
    'BiPAP': 'bilevel positive airway pressure',
    'ELISA': 'enzyme-linked immunosorbent assay',
    'ETCO2': 'end-tidal carbon dioxide',
    'FLACC': 'Face Legs Activity Cry Consolability pain scale',
    'FOOSH': 'fall on outstretched hand',
    'GTPAL': 'gravida, term, preterm, abortion, living',
    'HAGMA': 'high anion-gap metabolic acidosis',
    'HELLP': 'hemolysis, elevated liver enzymes, and low platelets syndrome',
    'HbA1c': 'hemoglobin A1c',
    'MRONJ': 'medication-related osteonecrosis of the jaw',
    'NAPQI': 'N-acetyl-p-benzoquinone imine',
    'NIOSH': 'National Institute for Occupational Safety and Health',
    'NSAID': 'nonsteroidal anti-inflammatory drug',
    'NSCLC': 'non-small-cell lung cancer',
    'POLST': 'Physician Orders for Life-Sustaining Treatment',
    'PUPPP': 'pruritic urticarial papules and plaques of pregnancy',
    'PaCO2': 'partial pressure of arterial carbon dioxide',
    'SGLT2': 'sodium-glucose cotransporter 2',
    'SIADH': 'syndrome of inappropriate antidiuretic hormone',
    'STEMI': 'ST-segment-elevation myocardial infarction',
    'TOLAC': 'trial of labor after cesarean',
    'TORCH': 'TORCH congenital infections',
    'TRALI': 'transfusion-related acute lung injury',
    'ABL1': 'ABL1 gene',
    'ADHD': 'attention-deficit/hyperactivity disorder',
    'AFib': 'atrial fibrillation',
    'AIHA': 'autoimmune hemolytic anemia',
    'ANCA': 'antineutrophil cytoplasmic antibody',
    'APAP': 'acetaminophen',
    'ARDS': 'acute respiratory distress syndrome',
    'ASAP': 'as soon as possible',
    'ATRA': 'all-trans retinoic acid',
    'BCMA': 'barcode medication administration',
    'BHCG': 'beta human chorionic gonadotropin',
    'CABG': 'coronary artery bypass grafting',
    'CD45': 'leukocyte common antigen',
    'CFTR': 'cystic fibrosis transmembrane conductance regulator',
    'CIDP': 'chronic inflammatory demyelinating polyneuropathy',
    'CIWA': 'Clinical Institute Withdrawal Assessment',
    'CLSI': 'Clinical and Laboratory Standards Institute',
    'COPD': 'chronic obstructive pulmonary disease',
    'CPAP': 'continuous positive airway pressure',
    'CRRT': 'continuous renal replacement therapy',
    'CRVO': 'central retinal vein occlusion',
    'CTPA': 'CT pulmonary angiogram',
    'CURB': 'CURB-65 pneumonia severity score',
    'DAPT': 'dual antiplatelet therapy',
    'DOAC': 'direct oral anticoagulant',
    'DPP4': 'dipeptidyl peptidase-4',
    'DRUJ': 'distal radioulnar joint',
    'EC50': 'half-maximal effective concentration',
    'ECMO': 'extracorporeal membrane oxygenation',
    'ED50': 'median effective dose',
    'EDTA': 'ethylenediaminetetraacetic acid',
    'EGFR': 'epidermal growth factor receptor',
    'ERCP': 'endoscopic retrograde cholangiopancreatography',
    'ESBL': 'extended-spectrum beta-lactamase',
    'ESRD': 'end-stage renal disease',
    'FFPE': 'formalin-fixed paraffin-embedded',
    'FISH': 'fluorescence in situ hybridization',
    'FSGS': 'focal segmental glomerulosclerosis',
    'GERD': 'gastroesophageal reflux disease',
    'GLP1': 'glucagon-like peptide-1',
    'GNDC': 'gram-negative diplococci',
    'GPCR': 'G protein-coupled receptor',
    'GVHD': 'graft-versus-host disease',
    'HCO3': 'bicarbonate',
    'HDFN': 'hemolytic disease of the fetus and newborn',
    'HER2': 'human epidermal growth factor receptor 2',
    'HFMD': 'hand-foot-and-mouth disease',
    'HOCM': 'hypertrophic obstructive cardiomyopathy',
    'HPLC': 'high-performance liquid chromatography',
    'IABP': 'intra-aortic balloon pump',
    'IANB': 'inferior alveolar nerve block',
    'ISMP': 'Institute for Safe Medication Practices',
    'IUGR': 'intrauterine growth restriction',
    'IVIG': 'intravenous immunoglobulin',
    'JAK2': 'Janus kinase 2',
    'LABA': 'long-acting beta agonist',
    'LAFW': 'laminar airflow workbench',
    'LASA': 'look-alike sound-alike',
    'LBBB': 'left bundle branch block',
    'LD50': 'median lethal dose',
    'LEMS': 'Lambert-Eaton myasthenic syndrome',
    'LGIB': 'lower gastrointestinal bleed',
    'LMWH': 'low-molecular-weight heparin',
    'LTBI': 'latent tuberculosis infection',
    'LUTS': 'lower urinary tract symptoms',
    'LVEF': 'left ventricular ejection fraction',
    'MAHA': 'microangiopathic hemolytic anemia',
    'MAOI': 'monoamine oxidase inhibitor',
    'MCHC': 'mean corpuscular hemoglobin concentration',
    'MDAC': 'multiple-dose activated charcoal',
    'MRSA': 'methicillin-resistant Staphylococcus aureus',
    'NAAT': 'nucleic acid amplification test',
    'OBRA': 'Omnibus Budget Reconciliation Act',
    'OGTT': 'oral glucose tolerance test',
    'ORIF': 'open reduction internal fixation',
    'PCWP': 'pulmonary capillary wedge pressure',
    'PEEP': 'positive end-expiratory pressure',
    'PERC': 'pulmonary embolism rule-out criteria',
    'PHTN': 'pulmonary hypertension',
    'PKD1': 'polycystic kidney disease 1',
    'POAG': 'primary open-angle glaucoma',
    'PRBC': 'packed red blood cells',
    'PaO2': 'partial pressure of arterial oxygen',
    'RAPD': 'relative afferent pupillary defect',
    'RBBB': 'right bundle branch block',
    'REMS': 'Risk Evaluation and Mitigation Strategy',
    'RIPE': 'rifampin, isoniazid, pyrazinamide, ethambutol',
    'ROSC': 'return of spontaneous circulation',
    'RPGN': 'rapidly progressive glomerulonephritis',
    'SABA': 'short-acting beta agonist',
    'SBAR': 'Situation-Background-Assessment-Recommendation',
    'SCLC': 'small-cell lung cancer',
    'SNAP': 'Supplemental Nutrition Assistance Program',
    'SNRI': 'serotonin-norepinephrine reuptake inhibitor',
    'SPEP': 'serum protein electrophoresis',
    'SSRI': 'selective serotonin reuptake inhibitor',
    'SpO2': 'oxygen saturation',
    'TACO': 'transfusion-associated circulatory overload',
    'TD50': 'median toxic dose',
    'TIBC': 'total iron-binding capacity',
    'TIPS': 'transjugular intrahepatic portosystemic shunt',
    'UGIB': 'upper gastrointestinal bleed',
    'VBAC': 'vaginal birth after cesarean',
    'VEGF': 'vascular endothelial growth factor',
    'VGCC': 'voltage-gated calcium channel',
    'XIII': '13',
    'aPTT': 'activated partial thromboplastin time',
    'AAT': 'alpha-1 antitrypsin',
    'ABG': 'arterial blood gas',
    'ABO': 'ABO blood group',
    'ACL': 'anterior cruciate ligament',
    'ACS': 'acute coronary syndrome',
    'ADH': 'antidiuretic hormone',
    'AFB': 'acid-fast bacilli',
    'AFP': 'alpha-fetoprotein',
    'AHG': 'anti-human globulin',
    'AIN': 'acute interstitial nephritis',
    'AKI': 'acute kidney injury',
    'ALC': 'absolute lymphocyte count',
    'ALL': 'acute lymphoblastic leukemia',
    'ALS': 'amyotrophic lateral sclerosis',
    'ALT': 'alanine aminotransferase',
    'AMA': 'against medical advice',
    'AMD': 'age-related macular degeneration',
    'AML': 'acute myeloid leukemia',
    'AMR': 'antibody-mediated rejection',
    'ANA': 'antinuclear antibody',
    'ANC': 'absolute neutrophil count',
    'APL': 'acute promyelocytic leukemia',
    'ASA': 'aspirin',
    'AST': 'aspartate aminotransferase',
    'ATD': 'antithyroid drug',
    'ATN': 'acute tubular necrosis',
    'AUC': 'area under the curve',
    'AVN': 'avascular necrosis',
    'BBB': 'bundle branch block',
    'BCG': 'Bacillus Calmette-Guérin',
    'BCR': 'breakpoint cluster region',
    'BNP': 'B-type natriuretic peptide',
    'BOO': 'bladder outlet obstruction',
    'BOP': 'bleeding on probing',
    'BPH': 'benign prostatic hyperplasia',
    'BSC': 'biological safety cabinet',
    'BUD': 'beyond-use date',
    'BUN': 'blood urea nitrogen',
    'BVM': 'bag-valve mask',
    'CAD': 'coronary artery disease',
    'CAL': 'clinical attachment level',
    'CAP': 'College of American Pathologists',
    'CBC': 'complete blood count',
    'CBD': 'common bile duct',
    'CD4': 'cluster of differentiation 4',
    'CD8': 'cluster of differentiation 8',
    'CEJ': 'cementoenamel junction',
    'CHF': 'congestive heart failure',
    'CHX': 'chlorhexidine',
    'CKD': 'chronic kidney disease',
    'CLL': 'chronic lymphocytic leukemia',
    'CML': 'chronic myeloid leukemia',
    'CMV': 'cytomegalovirus',
    'CNS': 'central nervous system',
    'COX': 'cyclooxygenase',
    'CPR': 'cardiopulmonary resuscitation',
    'CRE': 'carbapenem-resistant Enterobacterales',
    'CSF': 'cerebrospinal fluid',
    'CVA': 'cerebrovascular accident',
    'CVP': 'central venous pressure',
    'CXR': 'chest radiograph',
    'CYP': 'cytochrome P450',
    'DAT': 'direct antiglobulin test',
    'DEA': 'Drug Enforcement Administration',
    'DIC': 'disseminated intravascular coagulation',
    'DIP': 'distal interphalangeal',
    'DIY': 'do-it-yourself',
    'DKA': 'diabetic ketoacidosis',
    'DNA': 'deoxyribonucleic acid',
    'DNR': 'do not resuscitate',
    'DOB': 'date of birth',
    'DRE': 'digital rectal examination',
    'DVT': 'deep vein thrombosis',
    'EBV': 'Epstein-Barr virus',
    'ECG': 'electrocardiogram',
    'EDD': 'estimated due date',
    'EEG': 'electroencephalogram',
    'EHR': 'electronic health record',
    'EMG': 'electromyography',
    'ETT': 'endotracheal tube',
    'FFP': 'fresh frozen plasma',
    'FIT': 'fecal immunochemical test',
    'FNA': 'fine-needle aspiration',
    'FT4': 'free thyroxine',
    'GAS': 'group A Streptococcus',
    'GBM': 'glomerular basement membrane',
    'GBS': 'Guillain-Barré syndrome',
    'GCS': 'Glasgow Coma Scale',
    'GDM': 'gestational diabetes mellitus',
    'GEJ': 'gastroesophageal junction',
    'GFR': 'glomerular filtration rate',
    'GMS': 'Grocott methenamine silver',
    'GPA': 'granulomatosis with polyangiitis',
    'GTT': 'glucose tolerance test',
    'HHS': 'hyperosmolar hyperglycemic state',
    'HIT': 'heparin-induced thrombocytopenia',
    'HIV': 'human immunodeficiency virus',
    'HLA': 'human leukocyte antigen',
    'HOB': 'head of bed',
    'HPV': 'human papillomavirus',
    'HSV': 'herpes simplex virus',
    'HTN': 'hypertension',
    'HTR': 'hemolytic transfusion reaction',
    'HUS': 'hemolytic uremic syndrome',
    'Hct': 'hematocrit',
    'I&O': 'intake and output',
    'IAN': 'inferior alveolar nerve',
    'IAT': 'indirect antiglobulin test',
    'IBD': 'inflammatory bowel disease',
    'IBW': 'ideal body weight',
    'ICH': 'intracerebral hemorrhage',
    'ICP': 'intracranial pressure',
    'ICS': 'inhaled corticosteroid',
    'ICU': 'intensive care unit',
    'IDM': 'infant of diabetic mother',
    'IHC': 'immunohistochemistry',
    'IIH': 'idiopathic intracranial hypertension',
    'III': '3',
    'INH': 'isoniazid',
    'INO': 'internuclear ophthalmoplegia',
    'INR': 'international normalized ratio',
    'IOP': 'intraocular pressure',
    'IPF': 'idiopathic pulmonary fibrosis',
    'ISH': 'in situ hybridization',
    'ITP': 'immune thrombocytopenia',
    'IUP': 'intrauterine pregnancy',
    'IgA': 'immunoglobulin A',
    'IgD': 'immunoglobulin D',
    'IgE': 'immunoglobulin E',
    'IgG': 'immunoglobulin G',
    'IgM': 'immunoglobulin M',
    'JVD': 'jugular venous distention',
    'JVP': 'jugular venous pressure',
    'KOH': 'potassium hydroxide',
    'KUB': 'kidneys, ureters, bladder radiograph',
    'LAD': 'left anterior descending artery',
    'LDH': 'lactate dehydrogenase',
    'LLQ': 'left lower quadrant',
    'LMN': 'lower motor neuron',
    'LMP': 'last menstrual period',
    'LOC': 'level of consciousness',
    'LOD': 'limit of detection',
    'LPS': 'lipopolysaccharide',
    'LUQ': 'left upper quadrant',
    'MAC': 'minimum alveolar concentration',
    'MAP': 'mean arterial pressure',
    'MCD': 'minimal change disease',
    'MCI': 'mild cognitive impairment',
    'MCP': 'metacarpophalangeal',
    'MCV': 'mean corpuscular volume',
    'MDR': 'multidrug-resistant',
    'MDS': 'myelodysplastic syndrome',
    'MHC': 'major histocompatibility complex',
    'MIC': 'minimum inhibitory concentration',
    'MLF': 'medial longitudinal fasciculus',
    'MLS': 'medical laboratory science',
    'MMR': 'mismatch repair',
    'MPN': 'myeloproliferative neoplasm',
    'MPO': 'myeloperoxidase',
    'MPV': 'mean platelet volume',
    'MRI': 'magnetic resonance imaging',
    'MRN': 'medical record number',
    'MSI': 'microsatellite instability',
    'MTX': 'methotrexate',
    'NAC': 'N-acetylcysteine',
    'NBF': 'neutral buffered formalin',
    'NGS': 'next-generation sequencing',
    'NGT': 'nasogastric tube',
    'NMS': 'neuroleptic malignant syndrome',
    'NNH': 'number needed to harm',
    'NNT': 'number needed to treat',
    'NPH': 'neutral protamine Hagedorn insulin',
    'NPO': 'nothing by mouth',
    'NPV': 'negative predictive value',
    'NST': 'nonstress test',
    'NUG': 'necrotizing ulcerative gingivitis',
    'OLP': 'oral lichen planus',
    'OTC': 'over-the-counter',
    'PAS': 'periodic acid-Schiff',
    'PCA': 'patient-controlled analgesia',
    'PCC': 'prothrombin complex concentrate',
    'PCI': 'percutaneous coronary intervention',
    'PCR': 'polymerase chain reaction',
    'PDA': 'patent ductus arteriosus',
    'PDL': 'periodontal ligament',
    'PEG': 'polyethylene glycol',
    'PET': 'positron emission tomography',
    'PID': 'pelvic inflammatory disease',
    'PIP': 'proximal interphalangeal',
    'PNH': 'paroxysmal nocturnal hemoglobinuria',
    'PPD': 'purified protein derivative',
    'PPE': 'personal protective equipment',
    'PPH': 'postpartum hemorrhage',
    'PPI': 'proton pump inhibitor',
    'PPV': 'positive predictive value',
    'PR3': 'proteinase 3',
    'PRN': 'as needed',
    'PSA': 'prostate-specific antigen',
    'PSI': 'pneumonia severity index',
    'PTT': 'partial thromboplastin time',
    'PVR': 'pulmonary vascular resistance',
    'QRS': 'QRS complex',
    'RAI': 'radioactive iodine',
    'RAS': 'renal artery stenosis',
    'RBC': 'red blood cell',
    'RCA': 'right coronary artery',
    'RCC': 'renal cell carcinoma',
    'RCT': 'randomized controlled trial',
    'RDS': 'respiratory distress syndrome',
    'RDW': 'red cell distribution width',
    'RLQ': 'right lower quadrant',
    'RNA': 'ribonucleic acid',
    'ROM': 'range of motion',
    'RPE': 'retinal pigment epithelium',
    'RSV': 'respiratory syncytial virus',
    'RUQ': 'right upper quadrant',
    'SAH': 'subarachnoid hemorrhage',
    'SCC': 'squamous cell carcinoma',
    'SCI': 'spinal cord injury',
    'SDF': 'silver diamine fluoride',
    'SGA': 'small for gestational age',
    'SJS': 'Stevens-Johnson syndrome',
    'SLE': 'systemic lupus erythematosus',
    'SOP': 'standard operating procedure',
    'SRP': 'scaling and root planing',
    'SSA': 'Sjögren syndrome antigen A',
    'SSC': 'stainless steel crown',
    'SSI': 'surgical site infection',
    'STI': 'sexually transmitted infection',
    'SVT': 'supraventricular tachycardia',
    'TCA': 'tricyclic antidepressant',
    'TEN': 'toxic epidermal necrolysis',
    'THC': 'tetrahydrocannabinol',
    'TIA': 'transient ischemic attack',
    'TKI': 'tyrosine kinase inhibitor',
    'TPN': 'total parenteral nutrition',
    'TPO': 'thyroid peroxidase',
    'TSH': 'thyroid-stimulating hormone',
    'TST': 'tuberculin skin test',
    'TTN': 'transient tachypnea of the newborn',
    'TTP': 'thrombotic thrombocytopenic purpura',
    'UAP': 'unlicensed assistive personnel',
    'UFH': 'unfractionated heparin',
    'UIP': 'usual interstitial pneumonia',
    'UMN': 'upper motor neuron',
    'UOP': 'urine output',
    'USP': 'United States Pharmacopeia',
    'UTI': 'urinary tract infection',
    'VPA': 'valproic acid',
    'VRE': 'vancomycin-resistant enterococci',
    'WBC': 'white blood cell',
    'WCT': 'wide-complex tachycardia',
    'WIC': 'Women Infants and Children program',
    
    
    
    'hCG': 'human chorionic gonadotropin',
    'AF': 'atrial fibrillation',
    'AG': 'anion gap',
    'AP': 'anteroposterior',
    'AR': 'aortic regurgitation',
    'AS': 'aortic stenosis',
    'BP': 'blood pressure',
    'CF': 'cystic fibrosis',
    'CK': 'creatine kinase',
    'CL': 'contact lens',
    'CN': 'cranial nerve',
    'CT': 'computed tomography',
    'CV': 'coefficient of variation',
    'DM': 'diabetes mellitus',
    'Dx': 'diagnosis',
    'EM': 'electron microscopy',
    'ER': 'emergency room',
    'FQ': 'fluoroquinolone',
    'GA': 'general anesthesia',
    'GI': 'gastrointestinal',
    'GN': 'glomerulonephritis',
    'HD': 'hemodialysis',
    'HF': 'heart failure',
    'HR': 'heart rate',
    'HS': 'hypersensitivity',
    'Hx': 'history',
    'IF': 'immunofluorescence',
    'II': '2',
    'IM': 'intramuscular',
    'IV': 'intravenous',
    'LA': 'local anesthesia',
    'LE': 'leukocyte esterase',
    'LP': 'lumbar puncture',
    'LV': 'left ventricle',
    'MI': 'myocardial infarction',
    'MR': 'mitral regurgitation',
    'MS': 'multiple sclerosis',
    'NM': 'neuromuscular',
    'OA': 'osteoarthritis',
    'OB': 'obstetrics',
    'OD': 'overdose',
    'OR': 'operating room',
    'PA': 'posteroanterior',
    'PD': 'peritoneal dialysis',
    'PE': 'pulmonary embolism',
    'PK': 'pharmacokinetics',
    'PT': 'prothrombin time',
    'QA': 'quality assurance',
    'QC': 'quality control',
    'RA': 'rheumatoid arthritis',
    'RN': 'registered nurse',
    'RR': 'respiratory rate',
    'RV': 'right ventricle',
    'Rh': 'Rh blood group',
    'Rx': 'treatment',
    'SD': 'standard deviation',
    'SG': 'specific gravity',
    
    'Sx': 'symptoms',
    'TB': 'tuberculosis',
    'Tx': 'treatment',
    'UA': 'urinalysis',
    'UC': 'ulcerative colitis',
    'US': 'ultrasound',
    'UV': 'ultraviolet',
    'VF': 'ventricular fibrillation',
    'VI': '6',
    'VS': 'vital signs',
    'VT': 'ventricular tachycardia',
    'XR': 'radiograph',
    'ZN': 'Ziehl-Neelsen',
    'vs': 'versus',
}


# Additional expansions from bank audit
TOKEN_EXPANSIONS.update({
    'ALARA': 'as low as reasonably achievable',
    'BP180': 'bullous pemphigoid antigen 180',
    'HELLP': 'hemolysis, elevated liver enzymes, and low platelets syndrome',
    'IVIVC': 'in vitro-in vivo correlation',
    'ADME': 'absorption, distribution, metabolism, and excretion',
    'ATFL': 'anterior talofibular ligament',
    'CAMP': 'Christie-Atkins-Munch-Petersen test',
    'CDX2': 'caudal-type homeobox 2',
    'CMOS': 'complementary metal-oxide semiconductor',
    'CRAO': 'central retinal artery occlusion',
    'CRVO': 'central retinal vein occlusion',
    'LAMP': 'loop-mediated isothermal amplification',
    'PAGE': 'polyacrylamide gel electrophoresis',
    'POEM': 'peroral endoscopic myotomy',
    'PPCP': "Pharmacists' Patient Care Process",
    'PSGN': 'poststreptococcal glomerulonephritis',
    'RARA': 'retinoic acid receptor alpha',
    'RhIg': 'Rh immunoglobulin',
    'SOAP': 'Subjective Objective Assessment Plan',
    'SYBR': 'SYBR green dye',
    'TP53': 'tumor protein p53',
    'TPSA': 'topological polar surface area',
    'ABC': 'airway breathing circulation',
    'ABL': 'Abelson kinase',
    'ABO': 'ABO blood group',
    'ACA': 'anterior cerebral artery',
    'ACD': 'anemia of chronic disease',
    'ACE': 'angiotensin-converting enzyme',
    'ADC': 'automated dispensing cabinet',
    'API': 'active pharmaceutical ingredient',
    'ARI': '5-alpha reductase inhibitor',
    'BCS': 'Biopharmaceutics Classification System',
    'BTK': 'Bruton tyrosine kinase',
    'CHB': 'complete heart block',
    'CMR': 'comprehensive medication review',
    'CNV': 'choroidal neovascularization',
    'CO2': 'carbon dioxide',
    'CRR': 'corrective action and root cause review',
    'DME': 'diabetic macular edema',
    'DUR': 'drug utilization review',
    'EPT': 'electric pulp testing',
    'FDI': 'FDI World Dental Federation notation',
    'FMH': 'fetomaternal hemorrhage',
    'GPF': 'greater palatine foramen',
    'HBD': 'hydrogen-bond donor',
    'HCV': 'hepatitis C virus',
    'HMB': 'HMB-45 melanocytic marker',
    'IAP': 'intrapartum antibiotic prophylaxis',
    'IPT': 'interim therapeutic restoration',
    'ISO': 'International Organization for Standardization',
    'IgA': 'immunoglobulin A',
    'IgD': 'immunoglobulin D',
    'IgE': 'immunoglobulin E',
    'IgG': 'immunoglobulin G',
    'IgM': 'immunoglobulin M',
    'LCL': 'lateral collateral ligament',
    'LES': 'lower esophageal sphincter',
    'LGI': 'lower gastrointestinal',
    'LN2': 'liquid nitrogen',
    'MAF': 'mutual adaptive file',
    'MCA': 'middle cerebral artery',
    'MCL': 'medial collateral ligament',
    'MDI': 'metered-dose inhaler',
    'MIH': 'molar-incisor hypomineralization',
    'MMP': 'matrix metalloproteinase',
    'MSA': 'middle superior alveolar',
    'MTM': 'medication therapy management',
    'MUE': 'medication use evaluation',
    'NSF': 'nephrogenic systemic fibrosis',
    'OAT': 'organic anion transporter',
    'OCT': 'organic cation transporter',
    'PCL': 'posterior cruciate ligament',
    'PEC': 'primary engineering control',
    'PML': 'personal medication list',
    'POD': 'postoperative day',
    'PPS': 'posterior palatal seal',
    'PSC': 'primary sclerosing cholangitis',
    'PSP': 'photostimulable phosphor',
    'PTX': 'pneumothorax',
    'PYR': 'pyrrolidonyl arylamidase',
    'QRS': 'QRS complex',
    'RME': 'rapid maxillary expansion',
    'RPD': 'removable partial denture',
    'SDS': 'sodium dodecyl sulfate',
    'SMA': 'superior mesenteric artery',
    'TAD': 'temporary anchorage device',
    'TTF': 'thyroid transcription factor',
    'UNG': 'uracil-N-glycosylase',
    'VAF': 'variant allele fraction',
    'VDO': 'vertical dimension of occlusion',
    'VDR': 'vertical dimension at rest',
    'WCT': 'wide-complex tachycardia',
    'AB': 'antibody',
    'AC': 'anterior chamber',
    'AV': 'atrioventricular',
    'BB': 'beta-blocker',
    'CD': 'complete denture',
    'CO': 'carbon monoxide',
    'CR': 'centric relation',
    'CS': 'cesarean section',
    'DR': 'diabetic retinopathy',
    'GC': 'Neisseria gonorrhoeae',
    'GP': 'gutta-percha',
    'GV': 'G.V.',
    'IR': 'insulin resistance',
    'JC': 'John Cunningham virus',
    'MB': 'mesiobuccal',
    'NG': 'nasogastric',
    'PR': 'PR interval',
    'RD': 'retinal detachment',
    'RT': 'reverse transcriptase',
    'Rh': 'Rh factor',
    'SI': 'suicidal ideation',
    'SR': 'sustained release',
    'SU': 'sulfonylurea',
    'TS': 'transition state',
})

# Token expansions from second audit

TOKEN_EXPANSIONS.update({
    'APGAR': 'Appearance Pulse Grimace Activity Respiration score',
    'ARPKD': 'autosomal recessive polycystic kidney disease',
    'HELLP': 'hemolysis, elevated liver enzymes, and low platelets syndrome',
    'NASBA': 'nucleic acid sequence-based amplification',
    'NSAID': 'nonsteroidal anti-inflammatory drug',
    'RMGIC': 'resin-modified glass ionomer cement',
    'ABL1': 'Abelson murine leukemia viral oncogene homolog 1',
    'AFLP': 'acute fatty liver of pregnancy',
    'AH50': 'alternative pathway hemolytic complement activity',
    'AION': 'anterior ischemic optic neuropathy',
    'AQP4': 'aquaporin-4',
    'BPPV': 'benign paroxysmal positional vertigo',
    'CAMP': 'Christie-Atkins-Munch-Petersen',
    'CH50': 'total hemolytic complement activity',
    'COL4': 'collagen type IV',
    'CRAO': 'central retinal artery occlusion',
    'CURB': 'confusion urea respiratory-rate blood-pressure pneumonia score',
    'DOPE': 'displacement obstruction pneumothorax equipment failure mnemonic',
    'KATP': 'ATP-sensitive potassium channel',
    'LADA': 'latent autoimmune diabetes in adults',
    'MACE': 'major adverse cardiovascular events',
    'MASD': 'moisture-associated skin damage',
    'MODY': 'maturity-onset diabetes of the young',
    'MPFL': 'medial patellofemoral ligament',
    'MPGN': 'membranoproliferative glomerulonephritis',
    'NSTE': 'non-ST-segment elevation',
    'PERC': 'pulmonary embolism rule-out criteria',
    'SNHL': 'sensorineural hearing loss',
    'SYBR': 'asymmetric cyanine nucleic-acid dye',
    'TMDD': 'target-mediated drug disposition',
    'ABO': 'Landsteiner blood-group system',
    'ASM': 'antiseizure medication',
    'BCR': 'breakpoint cluster region',
    'CAG': 'cytosine-adenine-guanine',
    'CAM': 'Confusion Assessment Method',
    'CLI': 'critical limb ischemia',
    'CMV': 'cytomegalovirus',
    'CNI': 'calcineurin inhibitor',
    'CO2': 'carbon dioxide',
    'COX': 'cyclooxygenase',
    'CPA': 'cerebellopontine angle',
    'CPP': 'cerebral perfusion pressure',
    'CST': 'central corneal thickness',
    'DAW': 'dispense as written',
    'ECC': 'early childhood caries',
    'ERM': 'epiretinal membrane',
    'FDI': 'Fédération Dentaire Internationale tooth notation',
    'GCA': 'giant cell arteritis',
    'GTN': 'gestational trophoblastic neoplasia',
    'HHV': 'human herpesvirus',
    'HMB': 'gp100 melanosome glycoprotein marker',
    'HPF': 'high-power field',
    'HZO': 'herpes zoster ophthalmicus',
    'IFG': 'impaired fasting glucose',
    'IOP': 'intraocular pressure',
    'ISO': 'International Organization for Standardization',
    'IUT': 'intrauterine transfusion',
    'IVF': 'in vitro fertilization',
    'IgA': 'immunoglobulin A',
    'IgD': 'immunoglobulin D',
    'IgE': 'immunoglobulin E',
    'IgG': 'immunoglobulin G',
    'IgM': 'immunoglobulin M',
    'JIA': 'juvenile idiopathic arthritis',
    'LHA': 'leeway space analysis',
    'LLE': 'lipophilic ligand efficiency',
    'MPA': 'microscopic polyangiitis',
    'MRG': 'mixed red-and-white lesion concern',
    'NPA': 'Nurse Practice Act',
    'NTI': 'narrow therapeutic index',
    'ORS': 'oral rehydration solution',
    'PAS': 'periodic acid Schiff stain',
    'PCT': 'procalcitonin',
    'PDR': 'proliferative diabetic retinopathy',
    'PHI': 'protected health information',
    'PHN': 'postherpetic neuralgia',
    'PYR': 'pyrrolidonyl arylamidase',
    'QRS': 'ventricular depolarization complex',
    'SDS': 'sodium dodecyl sulfate',
    'SEM': 'systolic ejection murmur',
    'TCS': 'topical corticosteroid',
    'TMA': 'transcription-mediated amplification',
    'TSH': 'thyroid-stimulating hormone',
    'TTF': 'thyroid transcription factor',
    'TZD': 'thiazolidinedione',
    'ULN': 'upper limit of normal',
    'VZV': 'varicella-zoster virus',
    'WCT': 'wide-complex tachycardia',
    'XLD': 'xylose lysine deoxycholate agar',
    'AD': 'autosomal dominant',
    'AV': 'atrioventricular',
    'CG': 'chorionic gonadotropin',
    'CK': 'creatine kinase',
    'CT': 'computed tomography',
    'DA': 'dopamine',
    'DB': 'distobuccal',
    'ID': 'iron deficiency',
    'IG': 'immune globulin',
    'IQ': 'intelligence quotient',
    'JE': 'junctional epithelium',
    'OH': 'orthostatic hypotension',
    'PR': 'P-R interval',
    'RF': 'rheumatoid factor',
    'RT': 'reverse-transcriptase',
    'TA': 'transfusion-associated allergic reaction',
    'TD': 'tardive dyskinesia',
    'TV': 'tidal volume',
})

# third selfref fix

TOKEN_EXPANSIONS.update({
    'TORCH': 'toxoplasma, other agents, rubella, cytomegalovirus, and herpes simplex congenital infection panel',
    'CURB': 'confusion, urea, respiratory rate, and blood pressure pneumonia severity score',
    'Rh': 'Rhesus',
    'ABL1': 'Abelson murine leukemia viral oncogene homolog 1',
    'QRS': 'ventricular depolarization complex',
    'ABO': 'Landsteiner blood-group system',
    'PR': 'P-R interval',
    'SYBR': 'asymmetric cyanine nucleic-acid dye',
    'FDI': 'Fédération Dentaire Internationale tooth notation',
    'HMB': 'gp100 melanosome glycoprotein marker',
})


# Remaining whole-word expansions
TOKEN_EXPANSIONS.update({
    'CYP3A4': 'cytochrome P450 3A4',
    'NSAIDs': 'nonsteroidal anti-inflammatory drugs',
    'GPCRs': 'G protein-coupled receptors',
    'HBsAg': 'hepatitis B surface antigen',
    'NSAID': 'nonsteroidal anti-inflammatory drug',
    'PLA2R': 'phospholipase A2 receptor',
    'SGLT2': 'sodium-glucose cotransporter 2',
    'CBCT': 'cone-beam computed tomography',
    'COL4': 'collagen type IV',
    'CPPS': 'chronic pelvic pain syndrome',
    'CSPs': 'compounded sterile preparations',
    'DOAC': 'direct oral anticoagulant',
    'ESBL': 'extended-spectrum beta-lactamase',
    'FPDs': 'fixed partial dentures',
    'G6PD': 'glucose-6-phosphate dehydrogenase',
    'GPCR': 'G protein-coupled receptor',
    'H2RA': 'histamine-2 receptor antagonist',
    'HBDs': 'hydrogen-bond donors',
    'ISMP': 'Institute for Safe Medication Practices',
    'LFTs': 'liver function tests',
    'LLHA': 'lower lingual holding arch',
    'MAOI': 'monoamine oxidase inhibitor',
    'MDIs': 'metered-dose inhalers',
    'NSTE': 'non-ST-segment elevation',
    'NiTi': 'nickel-titanium',
    'PBPs': 'penicillin-binding proteins',
    'PDMP': 'prescription drug monitoring program',
    'PERC': 'pulmonary embolism rule-out criteria',
    'PPAR': 'peroxisome proliferator-activated receptor',
    'SAAG': 'serum-ascites albumin gradient',
    'SCDs': 'sequential compression devices',
    'SDVs': 'single-dose vials',
    'SGLT': 'sodium-glucose cotransporter',
    'SSRI': 'selective serotonin reuptake inhibitor',
    'T1DM': 'type 1 diabetes mellitus',
    'T2DM': 'type 2 diabetes mellitus',
    'TADs': 'temporary anchorage devices',
    'TURP': 'transurethral resection of the prostate',
    'WBCs': 'white blood cells',
    'WCTs': 'wide-complex tachycardias',
    'ACS': 'acute coronary syndrome',
    'ADT': 'androgen deprivation therapy',
    'ANB': 'A-point nasion B-point angle',
    'APF': 'acidulated phosphate fluoride',
    'ASB': 'asymptomatic bacteriuria',
    'ATP': 'adenosine triphosphate',
    'BMS': 'burning mouth syndrome',
    'BPO': 'benzoyl peroxide',
    'BUD': 'beyond-use date',
    'CCD': 'charge-coupled device',
    'CSP': 'compounded sterile preparation',
    'CYP': 'cytochrome P450',
    'DHT': 'dihydrotestosterone',
    'DIF': 'direct immunofluorescence',
    'FPD': 'fixed partial denture',
    'HBD': 'hydrogen-bond donor',
    'HPV': 'human papillomavirus',
    'INH': 'isoniazid',
    'IOP': 'intraocular pressure',
    'ISD': 'intrinsic sphincter deficiency',
    'LFT': 'liver function test',
    'MAO': 'monoamine oxidase',
    'MDI': 'metered-dose inhaler',
    'NOM': 'nonoperative management',
    'OTC': 'over-the-counter',
    'PAS': 'periodic acid Schiff stain',
    'PBP': 'penicillin-binding protein',
    'PDM': 'prescription drug monitoring',
    'PPI': 'proton pump inhibitor',
    'PUD': 'peptic ulcer disease',
    'RPI': 'rest proximal-plate I-bar clasp',
    'SCD': 'sequential compression device',
    'SDV': 'single-dose vial',
    'TAD': 'temporary anchorage device',
    'TMJ': 'temporomandibular joint',
    'TTF': 'thyroid transcription factor',
    'USP': 'United States Pharmacopeia',
    'WBC': 'white blood cell',
    'WCT': 'wide-complex tachycardia',
    'XCP': 'extension cone paralleling',
    'ZOE': 'zinc oxide eugenol',
    'DM': 'diabetes mellitus',
    'FH': 'fundal height',
    'SS': 'stainless steel',
})


# Fourth remaining batch
TOKEN_EXPANSIONS.update({
    'EUCAST': 'European Committee on Antimicrobial Susceptibility Testing',
    'ADPIE': 'Assessment Diagnosis Planning Implementation Evaluation',
    'CLOGP': 'calculated octanol-water partition coefficient',
    'HBsAg': 'hepatitis B surface antigen',
    'SOX10': 'SRY-box transcription factor 10',
    'START': 'Simple Triage and Rapid Treatment',
    'V617F': 'valine-to-phenylalanine mutation at position 617',
    'VAERS': 'Vaccine Adverse Event Reporting System',
    'ARNI': 'angiotensin receptor-neprilysin inhibitor',
    'BPMH': 'best possible medication history',
    'CSTD': 'closed-system transfer device',
    'FAST': 'Face Arm Speech Time stroke screen',
    'FBAO': 'foreign-body airway obstruction',
    'HBAs': 'hydrogen-bond acceptors',
    'LogP': 'octanol-water partition coefficient',
    'MAPK': 'mitogen-activated protein kinase',
    'NIPT': 'noninvasive prenatal testing',
    'PDSA': 'Plan-Do-Study-Act',
    'PROM': 'prelabor rupture of membranes',
    'RSBI': 'rapid shallow breathing index',
    'SDOH': 'social determinants of health',
    'SIDS': 'sudden infant death syndrome',
    'VKDB': 'vitamin K deficiency bleeding',
    'ACh': 'acetylcholine',
    'ALP': 'alkaline phosphatase',
    'ATO': 'arsenic trioxide',
    'BEA': 'bile esculin azide',
    'BLS': 'basic life support',
    'CCB': 'calcium channel blocker',
    'CCP': 'cyclic citrullinated peptide',
    'CO2': 'carbon dioxide',
    'DAG': 'diacylglycerol',
    'DEL': 'hydrophobic descriptor analysis',
    'DOT': 'directly observed therapy',
    'ELS': 'enhanced elimination strategy',
    'EVD': 'external ventricular drain',
    'FDA': 'Food and Drug Administration',
    'GER': 'gastroesophageal reflux',
    'GRK': 'G protein-coupled receptor kinase',
    'GSM': 'genitourinary symptom management',
    'HAE': 'hereditary angioedema',
    'HBA': 'hydrogen-bond acceptor',
    'IFA': 'indirect fluorescent antibody',
    'IP3': 'inositol trisphosphate',
    'IRS': 'insulin receptor substrate',
    'IgA': 'immunoglobulin A',
    'IgD': 'immunoglobulin D',
    'IgE': 'immunoglobulin E',
    'IgG': 'immunoglobulin G',
    'IgM': 'immunoglobulin M',
    'MBC': 'minimum bactericidal concentration',
    'MRT': 'mean residence time',
    'MTB': 'Mycobacterium tuberculosis',
    'MTP': 'massive transfusion protocol',
    'NAD': 'nicotinamide adenine dinucleotide',
    'NH2': 'amino group',
    'NTG': 'nitroglycerin',
    'OUD': 'opioid use disorder',
    'PKA': 'protein kinase A',
    'PKC': 'protein kinase C',
    'PLC': 'phospholipase C',
    'PML': 'promyelocytic leukemia',
    'PVA': 'polyvinyl alcohol',
    'RID': 'radial immunodiffusion',
    'RRT': 'rapid response team',
    'RTA': 'renal tubular acidosis',
    'RTK': 'receptor tyrosine kinase',
    'SAR': 'structure-activity relationship',
    'SEC': 'secondary engineering control',
    'SMS': 'short message service',
    'TTM': 'targeted temperature management',
    'UTP': 'uridine triphosphate',
    'VO2': 'oxygen consumption',
    'BE': 'bioequivalence',
    'C3': 'complement component 3',
    'C4': 'complement component 4',
    'DI': 'diabetes insipidus',
    'DT': 'delirium tremens',
    'ET': 'endotracheal',
    'Gi': 'inhibitory G protein',
    'Gq': 'Gq protein',
    'Gs': 'stimulatory G protein',
    'KB': 'Kleihauer-Betke',
    'MW': 'molecular weight',
    'NS': 'normal saline',
    'PV': 'polycythemia vera',
    'Sm': 'Smith antigen',
    'VC': 'vital capacity',
    'XV': 'X and V growth factors',
})


# Fifth remaining batch
TOKEN_EXPANSIONS.update({
    'ADMET': 'absorption distribution metabolism excretion toxicity',
    'HMB45': 'gp100 melanosome marker',
    'HbA1c': 'hemoglobin A1c',
    'PAINS': 'pan-assay interference compounds',
    'TURBT': 'transurethral resection of bladder tumor',
    'ACTH': 'adrenocorticotropic hormone',
    'AIDS': 'acquired immunodeficiency syndrome',
    'BRAF': 'B-Raf proto-oncogene',
    'BRUE': 'brief resolved unexplained event',
    'DHFR': 'dihydrofolate reductase',
    'FMEA': 'failure mode and effects analysis',
    'HDAC': 'histone deacetylase',
    'HERS': 'Hertwig epithelial root sheath',
    'MGUS': 'monoclonal gammopathy of undetermined significance',
    'PAPR': 'powered air-purifying respirator',
    'SCFP': 'sheathed continuous-flow procedure',
    'SLOB': 'same-lingual opposite-buccal',
    'CGM': 'continuous glucose monitoring',
    'CO2': 'carbon dioxide',
    'CSW': 'cerebral salt wasting',
    'DAH': 'diffuse alveolar hemorrhage',
    'DEJ': 'dentinoenamel junction',
    'ECR': 'edge cracked residual',
    'EDS': 'Ehlers-Danlos syndrome',
    'FDP': 'flexor digitorum profundus',
    'FSH': 'follicle-stimulating hormone',
    'HBV': 'hepatitis B virus',
    'HCC': 'hepatocellular carcinoma',
    'IBS': 'irritable bowel syndrome',
    'ICD': 'implantable cardioverter-defibrillator',
    'IPV': 'inactivated poliovirus vaccine',
    'LGE': 'local gingival erythema',
    'MDD': 'major depressive disorder',
    'OCP': 'oral contraceptive pill',
    'OKC': 'odontogenic keratocyst',
    'POI': 'premature ovarian insufficiency',
    'TDM': 'therapeutic drug monitoring',
    'TEA': 'total allowable error',
    'TSC': 'tuberous sclerosis complex',
    'UPJ': 'ureteropelvic junction',
    'VRF': 'vertical root fracture',
    'VTE': 'venous thromboembolism',
    'WFI': 'water for injection',
    'AI': 'aortic insufficiency',
    'AM': 'morning',
    'BV': 'bacterial vaginosis',
    'IP': 'intellectual property',
    'KS': 'Kaposi sarcoma',
    'MH': 'malignant hyperthermia',
    'O2': 'oxygen',
    'QT': 'ventricular repolarization interval',
})


# Final leftover expansions
TOKEN_EXPANSIONS.update({
    'IS': 'incentive spirometer',
    'QT': 'ventricular repolarization interval',
    'EBER': 'Epstein-Barr virus-encoded RNA',
    'TCBS': 'thiosulfate-citrate-bile salts-sucrose agar',
    'AL': 'amyloid light-chain',
    'AA': 'amyloid A',
    'MRD': 'minimal residual disease',
    'DHP': 'dihydropyridine',
    'EMS': 'emergency medical services',
    'FOBT': 'fecal occult blood test',
    'FiO2': 'fraction of inspired oxygen',
})

SPECIALTY_OVERRIDES: dict[str, dict[str, str]] = {
    'medicine': {
        'MS': 'mitral stenosis',
    },
    'neurology': {
        'MS': 'multiple sclerosis',
        'GBS': 'Guillain-Barré syndrome',
    },
    'pediatrics': {
        'PPV': 'positive-pressure ventilation',
        'GBS': 'group B Streptococcus',
    },
    'obgyn': {
        'GBS': 'group B Streptococcus',
    },
    'maternity': {
        'GBS': 'group B Streptococcus',
    },
    'cardiology': {
        'MS': 'mitral stenosis',
        'AS': 'aortic stenosis',
        'MR': 'mitral regurgitation',
        'AR': 'aortic regurgitation',
        'HF': 'heart failure',
        'HD': 'heart disease',
    },
    'pharmacy': {
        'PD': 'pharmacodynamics',
        'PK': 'pharmacokinetics',
        'OD': 'overdose',
        'HD': 'hemodialysis',
    },
    'pharmacokinetics': {
        'PD': 'pharmacodynamics',
        'PK': 'pharmacokinetics',
    },
    'pharmaceutics': {
        'PD': 'pharmacodynamics',
        'PK': 'pharmacokinetics',
    },
    'ophthalmology': {
        'OD': 'right eye',
        'OS': 'left eye',
        'OU': 'both eyes',
        'CL': 'contact lens',
    },
    'toxicology': {
        'OD': 'overdose',
    },
    'nursing': {
        'PD': 'pharmacodynamics',
    },
    'nephrology': {
        'PD': 'peritoneal dialysis',
        'HD': 'hemodialysis',
    },
    'hospital_pharmacy': {
        'HD': 'hazardous drug',
    },
    'blood_bank': {
        'IF': 'immunofluorescence',
    },
    'histopathology': {
        'IF': 'immunofluorescence',
        'EM': 'electron microscopy',
    },
    'lab_qa': {
        'QA': 'quality assurance',
        'QC': 'quality control',
    },
    'community': {
        'PPV': 'positive predictive value',
    },
    'critical_care': {
        'PPV': 'positive-pressure ventilation',
        'HD': 'hemodialysis',
    },
}


# Tokens intentionally left as standard scientific symbols / units / markers
KEEP = {
    "pH", "Na", "K", "Ca", "Mg", "Cl", "Fe", "N2", "H2O",
    "aVF", "aVL", "aVR",
    "A", "B", "C", "D",
    "X", "V",  # Haemophilus factors when alone after XV expand
}

_phrase_res = [(re.compile(p), r) for p, r in PHRASE_EXPANSIONS]


def _token_map_for(specialty: str | None, field: str | None) -> dict[str, str]:
    m = dict(TOKEN_EXPANSIONS)
    for key in (specialty, field):
        if key and key in SPECIALTY_OVERRIDES:
            m.update(SPECIALTY_OVERRIDES[key])
    return m


def expand_abbreviations(text: str, specialty: str | None = None, field: str | None = None) -> str:
    """Replace medical abbreviations with full words in question/choice text."""
    if not text:
        return text
    s = text
    for rx, repl in _phrase_res:
        s = rx.sub(repl, s)

    token_map = _token_map_for(specialty, field)
    # longest keys first
    keys = sorted(token_map.keys(), key=len, reverse=True)

    def repl_token(match: re.Match) -> str:
        tok = match.group(0)
        if tok in KEEP:
            return tok
        # Preserve leading option markers like "A) " already outside
        return token_map.get(tok, tok)

    # Match known tokens as whole words; allow optional trailing digits already in key
    if keys:
        # Escape and join
        pat = r"\b(" + "|".join(re.escape(k) for k in keys) + r")\b(?!-)"
        s = re.sub(pat, repl_token, s)

    # Lowercase clinical shorthand
    lower_map = {
        r"\bvs\.?\b": "versus",
        r"\bw/\b": "with",
        r"\bc/o\b": "complains of",
        r"\bh/o\b": "history of",
        r"\bs/p\b": "status post",
        r"\bmg\b": "milligrams",
        r"\bmcg\b": "micrograms",
        r"\bµg\b": "micrograms",
        r"\bkg\b": "kilograms",
        r"\bmL\b": "milliliters",
        r"\bml\b": "milliliters",
        r"\bmmHg\b": "millimeters of mercury",
        r"\bbpm\b": "beats per minute",
    }
    for p, r in lower_map.items():
        s = re.sub(p, r, s)

    # Clean doubled words from partial expansions
    s = re.sub(r"\bintravenous intravenous\b", "intravenous", s, flags=re.I)
    s = re.sub(r"\bST[_ ]?segment[- ]segment\b", "ST-segment", s, flags=re.I)
    s = re.sub(r"\blead lead\b", "lead", s, flags=re.I)
    s = re.sub(r"\bP-R interval interval\b", "P-R interval", s)
    s = re.sub(r"\binterval interval\b", "interval", s)
    s = re.sub(r"\bcomplex complex\b", "complex", s)
    s = re.sub(r"\benzyme enzyme\b", "enzyme", s)
    s = re.sub(r"\b5-5-alpha\b", "5-alpha", s)
    s = re.sub(r"\bhb A1c\b", "hemoglobin A1c", s, flags=re.I)
    s = re.sub(r"\bO2\b", "oxygen", s)
    s = re.sub(r"\bCO2\b", "carbon dioxide", s)
    s = re.sub(r"\bT-cell T-cell\b", "T-cell", s)
    s = re.sub(r"\band lead aVF\b", "and aVF", s)
    s = re.sub(r"\bACE inhibitor inhibitor\b", "ACE inhibitor", s, flags=re.I)
    s = re.sub(r"\s{2,}", " ", s)
    return s.strip()


def expand_question_dict(q: dict, specialty: str | None = None, field: str | None = None) -> dict:
    out = dict(q)
    for key in ("question", "answer", "explanation"):
        if key in out and isinstance(out[key], str):
            out[key] = expand_abbreviations(out[key], specialty, field)
    if "options" in out and isinstance(out["options"], list):
        out["options"] = [expand_abbreviations(o, specialty, field) for o in out["options"]]
    if "choice_explanations" in out and isinstance(out["choice_explanations"], dict):
        out["choice_explanations"] = {
            k: expand_abbreviations(v, specialty, field) for k, v in out["choice_explanations"].items()
        }
    # Keep answer letter prefix consistent with expanded option text
    if out.get("answer") and out.get("options"):
        # If answer letter still matches an option start, prefer the expanded option string
        m = re.match(r"^([A-D])\)\s*", out["answer"])
        if m:
            letter = m.group(1)
            for opt in out["options"]:
                if opt.startswith(f"{letter})"):
                    out["answer"] = opt
                    break
    return out
