"""Generate Short MCQs via Perplexity API and return structured items."""

from __future__ import annotations

import json
import logging
import os
import re
from typing import Any

import httpx

log = logging.getLogger("charanas-input-bot.perplexity")

DEFAULT_API_URL = "https://api.perplexity.ai/chat/completions"
DEFAULT_MODEL = "sonar-pro"

MCQ_JSON_SCHEMA: dict[str, Any] = {
    "name": "short_mcq_batch",
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "questions": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "question": {"type": "string"},
                        "options": {
                            "type": "array",
                            "minItems": 4,
                            "maxItems": 4,
                            "items": {"type": "string"},
                        },
                        "answer_letter": {
                            "type": "string",
                            "enum": ["A", "B", "C", "D"],
                        },
                        "explanation": {"type": "string"},
                    },
                    "required": ["question", "options", "answer_letter", "explanation"],
                },
            }
        },
        "required": ["questions"],
    },
}


class PerplexityError(RuntimeError):
    """Raised when Perplexity generation fails."""


def api_key() -> str:
    return (
        os.getenv("PERPLEXITY_API_KEY")
        or os.getenv("PPLX_API_KEY")
        or ""
    ).strip()


def configured() -> bool:
    return bool(api_key())


def _strip_code_fence(text: str) -> str:
    t = text.strip()
    if t.startswith("```"):
        t = re.sub(r"^```(?:json)?\s*", "", t, count=1, flags=re.I)
        t = re.sub(r"\s*```$", "", t, count=1)
    return t.strip()


def _normalize_item(raw: dict[str, Any]) -> dict[str, Any] | None:
    question = str(raw.get("question") or "").strip()
    options = raw.get("options") or []
    if not isinstance(options, list):
        return None
    opts = [str(o).strip() for o in options]
    # Allow dict form {"A": "...", ...}
    if len(opts) != 4 and isinstance(raw.get("options"), dict):
        od = raw["options"]
        opts = [str(od.get(L) or od.get(L.lower()) or "").strip() for L in "ABCD"]
    if not question or len(opts) != 4 or any(not o for o in opts):
        return None
    # Drop leading "A)" labels if present — storage will re-label
    cleaned = []
    for i, o in enumerate(opts):
        cleaned.append(re.sub(rf"^{re.escape('ABCD'[i])}\)\s*", "", o, count=1, flags=re.I).strip())
    letter = str(raw.get("answer_letter") or raw.get("answer") or "").strip().upper()[:1]
    if letter not in "ABCD":
        # Try match full answer text
        ans = str(raw.get("answer") or "").strip()
        for i, o in enumerate(cleaned):
            if ans and (ans == o or ans.endswith(o) or o in ans):
                letter = "ABCD"[i]
                break
    if letter not in "ABCD":
        return None
    explanation = str(raw.get("explanation") or "").strip()
    return {
        "question": question,
        "options": cleaned,
        "answer_letter": letter,
        "explanation": explanation or "Generated by Perplexity.",
    }


def _parse_payload(content: str) -> list[dict[str, Any]]:
    text = _strip_code_fence(content)
    data: Any
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        # Extract first JSON object/array in the reply
        m = re.search(r"(\{[\s\S]*\}|\[[\s\S]*\])", text)
        if not m:
            raise PerplexityError("Perplexity reply was not valid JSON.")
        data = json.loads(m.group(1))

    if isinstance(data, dict):
        items = data.get("questions") or data.get("items") or data.get("mcqs")
        if items is None and {"question", "options"} <= set(data.keys()):
            items = [data]
    elif isinstance(data, list):
        items = data
    else:
        raise PerplexityError("Unexpected JSON shape from Perplexity.")

    if not isinstance(items, list) or not items:
        raise PerplexityError("Perplexity returned no questions.")

    out: list[dict[str, Any]] = []
    for raw in items:
        if not isinstance(raw, dict):
            continue
        item = _normalize_item(raw)
        if item:
            out.append(item)
    if not out:
        raise PerplexityError("Could not parse any valid Short MCQs from Perplexity.")
    return out


def _build_prompt(
    *,
    department_label: str,
    specialty_label: str,
    difficulty: str,
    count: int,
    topic: str,
) -> str:
    focus = topic.strip() if topic.strip() else specialty_label
    return (
        f"Generate exactly {count} original board-style Short MCQ questions for "
        f"{department_label} students studying {specialty_label}.\n"
        f"Difficulty target: {difficulty}.\n"
        f"Topic focus: {focus}.\n\n"
        "Rules:\n"
        "- Clinically accurate and coherent; no fake crisis wording on mild topics.\n"
        "- Expand abbreviations to full words in stems and choices.\n"
        "- Exactly 4 options per question; one best answer.\n"
        "- Options must be plausible distractors, not joke answers.\n"
        "- Do not number the stem; do not prefix options with A)/B)/C)/D).\n"
        "- explanation: 1–3 sentences teaching the correct answer.\n"
        f"- Return exactly {count} questions in the JSON schema."
    )


def generate_short_mcqs(
    *,
    department_label: str,
    specialty_label: str,
    difficulty: str,
    count: int,
    topic: str = "",
) -> list[dict[str, Any]]:
    """Call Perplexity and return normalized Short MCQ dicts."""
    key = api_key()
    if not key:
        raise PerplexityError(
            "Missing PERPLEXITY_API_KEY. Add it to question_input/.env and restart the input bot."
        )
    if count < 1 or count > 20:
        raise PerplexityError("Count must be between 1 and 20 for Perplexity generation.")

    api_url = (os.getenv("PERPLEXITY_API_URL") or DEFAULT_API_URL).strip()
    model = (os.getenv("PERPLEXITY_MODEL") or DEFAULT_MODEL).strip()
    prompt = _build_prompt(
        department_label=department_label,
        specialty_label=specialty_label,
        difficulty=difficulty,
        count=count,
        topic=topic,
    )

    payload: dict[str, Any] = {
        "model": model,
        "temperature": 0.2,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are a medical/dental education exam writer. "
                    "Output only JSON matching the requested schema."
                ),
            },
            {"role": "user", "content": prompt},
        ],
        "response_format": {
            "type": "json_schema",
            "json_schema": MCQ_JSON_SCHEMA,
        },
    }
    # Prefer knowledge for curriculum MCQs; still allow academic search if useful
    if "sonar" in model.lower():
        payload["disable_search"] = True

    headers = {
        "Authorization": f"Bearer {key}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }

    log.info("Calling Perplexity model=%s count=%s specialty=%s", model, count, specialty_label)
    try:
        with httpx.Client(timeout=120.0) as client:
            resp = client.post(api_url, headers=headers, json=payload)
    except httpx.HTTPError as exc:
        raise PerplexityError(f"Perplexity network error: {exc}") from exc

    if resp.status_code >= 400:
        # Retry once without response_format (some accounts/models differ)
        if resp.status_code in {400, 422} and "response_format" in payload:
            log.warning("Perplexity rejected response_format; retrying plain JSON prompt")
            payload.pop("response_format", None)
            payload["messages"][-1]["content"] += (
                "\n\nRespond with JSON only: "
                '{"questions":[{"question":"...","options":["...","...","...","..."],'
                '"answer_letter":"A","explanation":"..."}]}'
            )
            with httpx.Client(timeout=120.0) as client:
                resp = client.post(api_url, headers=headers, json=payload)
        if resp.status_code >= 400:
            detail = resp.text[:400]
            raise PerplexityError(f"Perplexity API {resp.status_code}: {detail}")

    body = resp.json()
    try:
        content = body["choices"][0]["message"]["content"]
    except (KeyError, IndexError, TypeError) as exc:
        raise PerplexityError(f"Unexpected Perplexity response: {body!r}"[:500]) from exc

    if isinstance(content, list):
        # Some APIs return content parts
        content = "".join(
            part.get("text", "") if isinstance(part, dict) else str(part) for part in content
        )

    items = _parse_payload(str(content))
    return items[:count]
