"""Persist user-entered content into department banks / custom folders."""

from __future__ import annotations

import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    from catalog import DEPARTMENTS
    from dedupe import DuplicateQuestionError, find_similar, iter_bank_questions
except ImportError:  # pragma: no cover
    from question_input.catalog import DEPARTMENTS
    from question_input.dedupe import DuplicateQuestionError, find_similar, iter_bank_questions

DIFFICULTIES = ("easy", "medium", "hard", "extreme")
CASE_DIFFS = ("easy", "medium", "hard")

__all__ = [
    "DuplicateQuestionError",
    "append_short_mcq",
    "append_case",
    "append_book",
    "save_pdf",
    "save_generated_topic_pdf",
    "bank_counts",
    "load_bank",
    "list_bank_questions",
    "delete_short_mcq",
    "list_books",
    "delete_book",
    "list_specialty_pdfs",
    "delete_pdf",
]


def _read_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def department_paths(field: str) -> dict[str, Path]:
    dep = DEPARTMENTS[field]
    return {
        "banks_dir": Path(dep["banks_dir"]),
        "custom_dir": Path(dep["custom_dir"]),
        "pdf_dir": Path(dep["pdf_dir"]),
    }


def _bank_stem(field: str, specialty: str) -> str:
    aliases = DEPARTMENTS[field].get("bank_aliases") or {}
    return aliases.get(specialty, specialty)


def load_bank(field: str, specialty: str) -> dict[str, list[dict]]:
    stem = _bank_stem(field, specialty)
    path = department_paths(field)["banks_dir"] / f"{stem}.json"
    if not path.exists():
        # Keep every specialty/curriculum wired even on first upload
        path.parent.mkdir(parents=True, exist_ok=True)
        _write_json(path, {d: [] for d in DIFFICULTIES})
    data = _read_json(path, {d: [] for d in DIFFICULTIES})
    for d in DIFFICULTIES:
        data.setdefault(d, [])
    return data


def append_short_mcq(
    field: str,
    specialty: str,
    difficulty: str,
    *,
    question: str,
    options: list[str],
    answer_letter: str,
    explanation: str = "",
    choice_explanations: dict[str, str] | None = None,
    source: str = "user_input",
    reject_similar: bool = True,
) -> dict[str, Any]:
    """Append one Short MCQ into the department specialty bank. Returns saved item.

    When reject_similar=True (default), raises DuplicateQuestionError if the stem
    is the same as or a close rephrase of any existing item in this bank.
    """
    if difficulty not in DIFFICULTIES:
        raise ValueError(f"invalid difficulty: {difficulty}")
    if len(options) != 4:
        raise ValueError("need exactly 4 options")
    letter = answer_letter.strip().upper()[:1]
    if letter not in "ABCD":
        raise ValueError("answer must be A, B, C, or D")

    labeled = []
    for i, text in enumerate(options):
        L = "ABCD"[i]
        t = text.strip()
        if re.match(rf"^{L}\)\s*", t, flags=re.I):
            labeled.append(re.sub(rf"^{L}\)\s*", f"{L}) ", t, count=1, flags=re.I))
        else:
            labeled.append(f"{L}) {t}")

    answer = labeled[ord(letter) - ord("A")]
    src = (source or "user_input").strip() or "user_input"
    default_exp = (
        "Generated by Perplexity." if src == "perplexity" else "User-submitted question."
    )
    exp = (explanation or "").strip() or default_exp
    cex: dict[str, str] = {}
    if isinstance(choice_explanations, dict):
        for L in "ABCD":
            text = str(choice_explanations.get(L) or choice_explanations.get(L.lower()) or "").strip()
            if text and text.lower() not in {
                "not the best answer for this item.",
                "not the best answer",
                "incorrect",
            }:
                cex[L] = text
    # Prefer authored per-choice rationales; otherwise leave empty so the study
    # bots can synthesize from the main explanation at reveal time.
    if letter not in cex and exp:
        cex[letter] = exp

    stem = _bank_stem(field, specialty)
    bank = load_bank(field, specialty)
    qtext = question.strip()

    if reject_similar:
        match, score = find_similar(qtext, iter_bank_questions(bank))
        if match is not None:
            mid = str(match.get("id") or "")
            mq = str(match.get("question") or "")
            raise DuplicateQuestionError(
                f"Similar to existing question (score={score:.2f}): {mq[:120]}",
                matched_id=mid or None,
                matched_question=mq,
                score=score,
            )

    idx = len(bank[difficulty])
    prefix = "pplx" if src == "perplexity" else "custom"
    item = {
        "id": f"{specialty}:{difficulty}:{prefix}:{idx}",
        "question": qtext,
        "options": labeled,
        "answer": answer,
        "explanation": exp,
        "choice_explanations": cex,
        "source": src,
        "curriculum": specialty,
        "added_at": datetime.now(timezone.utc).isoformat(),
    }
    bank[difficulty].append(item)
    path = department_paths(field)["banks_dir"] / f"{stem}.json"
    _write_json(path, bank)
    return item


def append_case(
    field: str,
    specialty: str,
    difficulty: str,
    *,
    title: str,
    stem: str,
    question: str,
    answer: str,
    discussion: str = "",
    book_hint: str = "",
) -> dict[str, Any]:
    if difficulty not in CASE_DIFFS:
        raise ValueError(f"invalid case difficulty: {difficulty}")
    custom_dir = department_paths(field)["custom_dir"]
    path = custom_dir / "cases" / f"{specialty}.json"
    data = _read_json(path, {d: [] for d in CASE_DIFFS})
    for d in CASE_DIFFS:
        data.setdefault(d, [])
    item = {
        "title": title.strip(),
        "stem": stem.strip(),
        "question": question.strip(),
        "answer": answer.strip(),
        "discussion": (discussion or "").strip() or "User-submitted case.",
        "book_hint": (book_hint or "").strip() or "Custom case",
        "source": "user_input",
        "added_at": datetime.now(timezone.utc).isoformat(),
    }
    data[difficulty].append(item)
    _write_json(path, data)
    return item


def append_book(field: str, specialty: str, title: str) -> str:
    custom_dir = department_paths(field)["custom_dir"]
    path = custom_dir / "books" / f"{specialty}.json"
    data = _read_json(path, [])
    if not isinstance(data, list):
        data = []
    title = title.strip()
    if title and title not in data:
        data.append(title)
        _write_json(path, data)
    return title


def save_pdf(field: str, specialty: str, src_path: Path, original_name: str) -> Path:
    pdf_dir = department_paths(field)["pdf_dir"] / "custom" / specialty
    pdf_dir.mkdir(parents=True, exist_ok=True)
    safe = re.sub(r"[^\w.\-]+", "_", original_name).strip("_") or "upload.pdf"
    if not safe.lower().endswith(".pdf"):
        safe += ".pdf"
    dest = pdf_dir / safe
    if dest.exists():
        stem = dest.stem
        dest = pdf_dir / f"{stem}_{int(datetime.now().timestamp())}.pdf"
    shutil.copy2(src_path, dest)
    meta_path = department_paths(field)["custom_dir"] / "pdfs" / f"{specialty}.json"
    meta = _read_json(meta_path, [])
    meta.append(
        {
            "file": dest.name,
            "original_name": original_name,
            "added_at": datetime.now(timezone.utc).isoformat(),
        }
    )
    _write_json(meta_path, meta)
    return dest


def save_generated_topic_pdf(
    field: str,
    specialty: str,
    src_path: Path,
    *,
    topic: str,
    stage: str = "",
    slide_count: int = 0,
    source: str = "perplexity",
) -> Path:
    """Save a generated topic PDF under pdfs/generated/ and mirror into pdfs/custom/.

    Dual-write keeps study-bot PDF menus working even if a caller only scans custom/.
    """
    pdf_base = department_paths(field)["pdf_dir"]
    pdf_root = pdf_base / "generated"
    if stage:
        pdf_dir = pdf_root / stage / specialty
    else:
        pdf_dir = pdf_root / specialty
    pdf_dir.mkdir(parents=True, exist_ok=True)
    safe_topic = re.sub(r"[^\w.\-]+", "_", topic.strip()).strip("_") or "topic"
    safe = f"{safe_topic[:70]}.pdf"
    dest = pdf_dir / safe
    if dest.exists():
        dest = pdf_dir / f"{dest.stem}_{int(datetime.now().timestamp())}.pdf"
    shutil.copy2(src_path, dest)

    # Mirror into custom/<specialty>/ so discovery cannot silently miss generated files.
    custom_dir = pdf_base / "custom" / specialty
    custom_dir.mkdir(parents=True, exist_ok=True)
    custom_dest = custom_dir / dest.name
    if not custom_dest.exists():
        shutil.copy2(dest, custom_dest)

    meta_path = department_paths(field)["custom_dir"] / "pdfs" / f"{specialty}.json"
    meta = _read_json(meta_path, [])
    meta.append(
        {
            "file": str(dest.relative_to(pdf_base)),
            "custom_file": str(custom_dest.relative_to(pdf_base)),
            "original_name": dest.name,
            "topic": topic,
            "stage": stage or None,
            "slide_count": slide_count,
            "source": source,
            "added_at": datetime.now(timezone.utc).isoformat(),
        }
    )
    _write_json(meta_path, meta)
    return dest


def bank_counts(field: str, specialty: str) -> dict[str, int]:
    bank = load_bank(field, specialty)
    return {d: len(bank.get(d) or []) for d in DIFFICULTIES}


def list_bank_questions(
    field: str,
    specialty: str,
    *,
    difficulty: str | None = None,
) -> list[dict[str, Any]]:
    """List Short MCQs for delete UI. difficulty=None means all levels."""
    bank = load_bank(field, specialty)
    levels = DIFFICULTIES if not difficulty or difficulty == "all" else (difficulty,)
    out: list[dict[str, Any]] = []
    for diff in levels:
        if diff not in DIFFICULTIES:
            continue
        for item in bank.get(diff) or []:
            if not isinstance(item, dict):
                continue
            qid = str(item.get("id") or "").strip()
            stem = str(item.get("question") or "").strip()
            if not qid and not stem:
                continue
            out.append(
                {
                    "id": qid or f"{specialty}:{diff}:anon:{len(out)}",
                    "difficulty": diff,
                    "question": stem,
                    "source": str(item.get("source") or ""),
                    "preview": (stem[:72] + "…") if len(stem) > 72 else stem,
                }
            )
    return out


def delete_short_mcq(field: str, specialty: str, question_id: str) -> dict[str, Any] | None:
    """Remove one Short MCQ by id. Returns the removed item, or None if not found."""
    qid = (question_id or "").strip()
    if not qid:
        return None
    stem = _bank_stem(field, specialty)
    bank = load_bank(field, specialty)
    removed: dict[str, Any] | None = None
    for diff in DIFFICULTIES:
        items = bank.get(diff) or []
        keep: list[dict] = []
        for item in items:
            if not isinstance(item, dict):
                continue
            if removed is None and str(item.get("id") or "").strip() == qid:
                removed = item
                continue
            keep.append(item)
        bank[diff] = keep
    if removed is None:
        return None
    path = department_paths(field)["banks_dir"] / f"{stem}.json"
    _write_json(path, bank)
    return removed


def list_books(field: str, specialty: str) -> list[str]:
    """Custom book titles only (not hardcoded study-bot defaults)."""
    custom_dir = department_paths(field)["custom_dir"]
    path = custom_dir / "books" / f"{specialty}.json"
    data = _read_json(path, [])
    if not isinstance(data, list):
        return []
    return [str(t).strip() for t in data if str(t).strip()]


def delete_book(field: str, specialty: str, title: str) -> bool:
    """Remove one custom book title. Returns True if something was removed."""
    title = (title or "").strip()
    if not title:
        return False
    custom_dir = department_paths(field)["custom_dir"]
    path = custom_dir / "books" / f"{specialty}.json"
    data = _read_json(path, [])
    if not isinstance(data, list):
        data = []
    new_data = [str(t) for t in data if str(t).strip() != title]
    if len(new_data) == len(data):
        return False
    _write_json(path, new_data)
    return True


def list_specialty_pdfs(field: str, specialty: str) -> list[dict[str, Any]]:
    """List discoverable custom/generated PDFs for a specialty (deduped by name)."""
    try:
        from pdf_discovery import find_specialty_pdfs
    except ImportError:  # pragma: no cover
        import sys

        root = Path(__file__).resolve().parents[1]
        if str(root) not in sys.path:
            sys.path.insert(0, str(root))
        from pdf_discovery import find_specialty_pdfs

    pdf_dir = department_paths(field)["pdf_dir"]
    paths = find_specialty_pdfs(pdf_dir, specialty)
    out: list[dict[str, Any]] = []
    for path in paths:
        try:
            rel = str(path.relative_to(pdf_dir))
        except ValueError:
            rel = path.name
        parts = Path(rel).parts
        kind = "generated" if parts and parts[0] == "generated" else "custom"
        out.append(
            {
                "name": path.name,
                "path": str(path),
                "rel": rel,
                "kind": kind,
                "preview": path.name if len(path.name) <= 60 else path.name[:57] + "…",
            }
        )
    return out


def delete_pdf(field: str, specialty: str, filename: str) -> list[Path]:
    """Delete a specialty PDF everywhere it appears (custom + generated mirrors).

    Also prunes matching rows from custom_content/pdfs/{specialty}.json.
    Returns the list of paths that were removed.
    """
    name = Path(filename or "").name
    if not name or not name.lower().endswith(".pdf"):
        return []

    pdf_base = department_paths(field)["pdf_dir"]
    removed: list[Path] = []
    seen: set[str] = set()

    candidates: list[Path] = [
        pdf_base / "custom" / specialty / name,
    ]
    gen_root = pdf_base / "generated"
    direct = gen_root / specialty / name
    candidates.append(direct)
    if gen_root.is_dir():
        for path in gen_root.glob(f"*/{specialty}/{name}"):
            candidates.append(path)
        # Also catch any deeper/other copies with the same filename under this specialty tree
        for path in gen_root.rglob(name):
            if specialty in path.parts:
                candidates.append(path)
    custom_copies = pdf_base / "custom" / specialty
    if custom_copies.is_dir():
        candidates.append(custom_copies / name)

    for path in candidates:
        try:
            resolved = str(path.resolve())
        except OSError:
            continue
        if resolved in seen:
            continue
        seen.add(resolved)
        if path.is_file():
            path.unlink()
            removed.append(path)

    meta_path = department_paths(field)["custom_dir"] / "pdfs" / f"{specialty}.json"
    meta = _read_json(meta_path, [])
    if isinstance(meta, list) and meta:
        pruned = []
        for row in meta:
            if not isinstance(row, dict):
                continue
            file_val = str(row.get("file") or "")
            custom_val = str(row.get("custom_file") or "")
            original = str(row.get("original_name") or "")
            if Path(file_val).name == name or Path(custom_val).name == name or original == name:
                continue
            pruned.append(row)
        if len(pruned) != len(meta):
            _write_json(meta_path, pruned)

    return removed
